/*
 * file generated by di_ctor_traits: di_ctor_traits.hpp
 */
#ifndef DI_CTOR_TRAITS_HPP
#define DI_CTOR_TRAITS_HPP

#include "given/ctors.hpp"

namespace boost {
namespace di {

template<>
struct ctor_traits<n::a>
{
    static void ctor(int);
};

template<>
struct ctor_traits<n::n1::b>
{
    static void ctor(int, double, const std::string &);
};

} // namespace di
} // namespace boost

#endif // DI_CTOR_TRAITS_HPP

